# Generated by Django 3.2.19 on 2023-05-29 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TabInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tab_instance_name', models.CharField(max_length=255, null=True, unique=True)),
                ('tab_instance_slug', models.SlugField(max_length=255, unique=True)),
                ('project_instance_tab_instance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tabinstances', to='core.projectinstance')),
            ],
        ),
    ]
