# Generated by Django 3.2.19 on 2023-05-29 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tabinstance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tabinstance',
            name='tab_instance_slug',
        ),
    ]
