# Generated by Django 3.2.19 on 2023-05-29 21:22

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_tabinstance_tab_instance_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabinstance',
            name='main_data',
            field=models.FileField(null=True, upload_to=core.models.project_data_file_path),
        ),
    ]
